[phases.setup]
nixPkgs = ["python311", "gcc"]

[phases.install]
cmds = ["cd server && pip install -r requirements.txt"]

[phases.build]
cmds = ["cd server && python3 manage.py collectstatic --noinput"]

[start]
cmd = "cd server && gunicorn djangoproj.wsgi --bind 0.0.0.0:$PORT"
